### ISSUE TITLE
wp standard handles name

### ISSUE THREAD

**Issue by EmranAhmed** [hasinhayder/themeforest-wp-theme-approval-checklist#4]
Found a `wp-standard-handles` names. Please take a look: [wp-standard-handles](https://github.com/grappler/wp-standard-handles). We can follow this :)

**Comment by hasinhayder** [comment]
It is already in the doc. See the bottom of this section https://github.com/hasinhayder/themeforest-wp-theme-approval-checklist#rename-your-script-and-css-handles

> For details you can check out this documentation by grappler - https://github.com/grappler/wp-standard-handles

**Comment by EmranAhmed** [comment]
Did not see that, thank you 👍
